name: presensiblebeacon
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter_icons:
  image_path: "assets/png/SplashPage_LogoAtmaJaya_1.png" 
  android: true
  ios: true

dependencies:
  flutter:
    sdk: flutter

  # Kumpulan Package

  # Icon Launcher
  flutter_launcher_icons: "^0.9.0"

  # Ikon dan Font
  cupertino_icons: ^1.0.2

  # Kostum Ikon dan Font
  font_awesome_flutter: ^9.0.0

  # Animasi progress dalam bentuk shimmer.
  shimmer: ^2.0.0

  # Bluetooth On / Off.
  # flutter_blue: ^0.8.0

  # Memanggil sistem untuk menghidupkan bluetooth.
  # system_setting: ^0.1.3

  # Fungsi Scanning Bluetooth.
  flutter_beacon: ^0.5.0
  
  # API.
  http: ^0.12.1

  # Local Storage
  shared_preferences: ^2.0.5

  # Transisi halaman dan routing.
  get: ^4.1.4
  
  # Jam
  intl: ^0.17.0

  # Menampilkan peringatan dalam bentuk toast.
  fluttertoast: ^8.0.7
  
  # Menampilkan animasi progress login pada login
  flutter_progress_hud: ^2.0.0

  # Permission GPS, Location
  # Package Lama
  # permission_handler: ^4.4.0+hotfix.2
  # permission_handler: ^4.4.0+hotfix.4
  # permission_handler: ^5.0.0
  permission_handler: ^8.1.6
  
  # Cek Koneksi Internet
  connectivity: ^3.0.6

  provider: ^6.0.2
  
  # Modal Alert
  sk_alert_dialog: ^1.0.0

  # Inisial Nama Icon
  flutter_initicon: ^2.0.0

  # Progress Bar Animation
  flutter_animation_progress_bar: ^2.0.0

  # Icons Pack
  flutter_icons: ^1.1.0

  # Spinner Kit
  flutter_spinkit: ^5.0.0

  # Menyesuaikan teks pada perubahan layar
  auto_size_text: ^2.1.0

  # Error Handling with Dialog
  # base_api_client: ^0.0.3
  # dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/images/error_icon.png
    - assets/images/background1.jpg
    - assets/images/not_found_icon.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: ProductSansRegular
      fonts:
        - asset: assets/fonts/Product_Sans/Product_Sans_Regular.ttf

    - family: ProductSansBold
      fonts:
        - asset: assets/fonts/Product_Sans/Product_Sans_Bold.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
